CREATE TABLE IF NOT EXISTS user (
    userId UUID PRIMARY KEY NOT NULL,
    firstName VARCHAR(100) NOT NULL,
    lastName VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password  VARCHAR(100) NOT NULL
);

